services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - '6379:6379'

  api:
    build: .
    restart: unless-stopped
    ports:
      - '3000:3000'
    environment:
      MONGODB_URI: mongodb://mongo:27017/edupath
      REDIS_URL: redis://redis:6379
      JWT_ACCESS_SECRET: change-me-in-prod-access
      JWT_REFRESH_SECRET: change-me-in-prod-refresh
      CORS_ORIGIN: http://localhost:5173
      FRONTEND_URL: http://localhost:5173
    depends_on:
      - mongo
      - redis

volumes:
  mongo_data:
