import { TeamMember } from './team-member.schema';

/** Seeded leadership profiles for About Us (admin can edit after seed). */
export const DEFAULT_TEAM_MEMBERS: Omit<TeamMember, 'createdAt' | 'updatedAt'>[] = [
  {
    name: 'Mehshar Khan',
    experience: '2 years',
    position: 'CEO',
    state: 'Maharashtra',
    imageUrl: '',
    order: 0,
    active: true,
  },
  {
    name: 'Sana Parveen',
    experience: '1 Year',
    position: 'Leader',
    contactNumber: '8005318751',
    state: 'Uttar Pradesh',
    instagram: 'sanaparveenofficial_',
    imageUrl: '',
    order: 1,
    active: true,
  },
  {
    name: 'Roshan Ameena',
    experience: '1 year',
    position: 'Leader',
    contactNumber: '9347432119',
    state: 'Telangana',
    instagram: 'roshanameena05',
    imageUrl: '',
    order: 2,
    active: true,
  },
  {
    name: 'Aliya Raini',
    experience: '1 year',
    position: 'Leader',
    contactNumber: '9335290192',
    state: 'Lucknow',
    instagram: 'aliyamusha',
    imageUrl: '',
    order: 3,
    active: true,
  },
  {
    name: 'Sofiya Ali',
    experience: '3 years',
    position: 'HR',
    contactNumber: '9302541424',
    state: 'Telangana',
    instagram: 'sofiyaali_9',
    imageUrl: '',
    order: 4,
    active: true,
  },
  {
    name: 'Shabnoor Shaikh',
    experience: '1 year',
    position: 'Leader',
    contactNumber: '7906052669',
    state: 'Uttarakhand',
    instagram: 'shabnoorsk_',
    instagramSecondary: 'ruhanixsafar',
    imageUrl: '',
    order: 5,
    active: true,
  },
];
